#!/bin/bash

COMPILE_DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))
SOLETTA_TARGET=$COMPILE_DIR/opt/solda-intel-galileo-gen2-soletta-master/sysroot/
source $COMPILE_DIR/common-compile.sh
# Don't forget to set PATH_TO_SDK. This script is worth looking into. Maybe
# it should be changed a bit in order to correct a few paths.
source $PATH_TO_SDK/opt/solda-intel-galileo-gen2-soletta-master/env.sh

mkdir -p $COMPILE_DIR/initramfs/dev
# SOL_CC is defined  in env.sh. This command will compile the soletta app
SOL_CC -o $COMPILE_DIR/initramfs/init $(find -name '*.c')
if [ $? -ne 0 ]; then
    exit 1
fi

pushd .

cd $COMPILE_DIR/initramfs/dev
sudo mknod -m 622 console c 5 1
sudo mknod -m 622 tty0 c 4 0

cd $COMPILE_DIR/initramfs
find . | cpio -H newc -o > $COMPILE_DIR/initramfs.cpio

cd $COMPILE_DIR
cat initramfs.cpio | gzip > initramfs.cpio.gz

sudo mount -o loop,offset=1048576 base.img /mnt
sudo cp initramfs.cpio.gz /mnt
sudo umount /mnt

popd
mkdir $PLATFORM_NAME
cp $COMPILE_DIR/base.img $PLATFORM_NAME/flash.img
cp $COMPILE_DIR/flash.sh $PLATFORM_NAME
zip -r output.zip $PLATFORM_NAME
